authors = ["Florian Oswald <florian.oswald@gmail.com>"]
name = "cudaVFI"
uuid = "0ee9aef2-6a58-11e8-011c-2bde8171ac5c"
version = "0.1.0"

[deps]
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
